export enum TipoPlantaEnum {
  SOJA = "SOJA",
  MILHO = "MILHO",
  FEIJAO = "FEIJAO"
}

export enum TipoSoloEnum {
  ARENOSO = "ARENOSO",
  ARGILOSO = "ARGILOSO",
  SILTOSO = "SILTOSO",
  MISTO = "MISTO",
  HUMIFERO = "HUMIFERO",
  CALCARIO = "CALCARIO",
  GLEISSOLO = "GLEISSOLO",
  LATOSSOLO = "LATOSSOLO",
  CAMBISSOLO = "CAMBISSOLO",
  ORGANOSSOLO = "ORGANOSSOLO",
  NEOSSOLO = "NEOSSOLO",
  PLANOSSOLO = "PLANOSSOLO",
  VERTISSOLO = "VERTISSOLO"
}