-- AlterTable
ALTER TABLE "analise_solo" ADD COLUMN     "k" DOUBLE PRECISION,
ADD COLUMN     "n" DOUBLE PRECISION,
ADD COLUMN     "p" DOUBLE PRECISION,
ADD COLUMN     "prnt" DOUBLE PRECISION,
ADD COLUMN     "valor_cultural" DOUBLE PRECISION;
