export enum TipoEtapaOperacaoEnum {
  PREPARO_SOLO = 'PREPARO_SOLO',
  SEMEADURA = 'SEMEADURA',
  APLICACAO_DEFENSIVO = 'APLICACAO_DEFENSIVO',
  APLICACAO_FERTILIZANTE = 'APLICACAO_FERTILIZANTE',
  IRRIGACAO = 'IRRIGACAO',
  COLHEITA = 'COLHEITA',
  OUTROS = 'OUTROS',
}
